;==============================================================================
; __        ____  ____   ____ ____   __  ____ ______  ______  
; \ \      / / /_| ___| / ___|___ \ / /_| ___/ ___\ \/ / __ ) 
;  \ \ /\ / / '_ \___ \| |     __) | '_ \___ \___ \\  /|  _ \ 
;   \ V  V /| (_) |__) | |___ / __/| (_) |__) |__) /  \| |_) |
;    \_/\_/  \___/____/ \____|_____|\___/____/____/_/\_\____/ 
;
; Western Design Center W65C265SXB Development Board Hardware Definitions
;------------------------------------------------------------------------------
; Copyright (C)2015 HandCoded Software Ltd.
; All rights reserved.
;
; This work is made available under the terms of the Creative Commons
; Attribution-NonCommercial-ShareAlike 4.0 International license. Open the
; following URL to see the details.
;
; http://creativecommons.org/licenses/by-nc-sa/4.0/
;
;==============================================================================
; Notes:
;
;------------------------------------------------------------------------------

OSC_FREQ        equ     3686400      	; SXB runs at 3.6864MHz
